// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukkttdtujfsfazenueuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVra3R0ZHR1amZzZmF6ZW51ZXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjE2MDksImV4cCI6MjA2OTAzNzYwOX0.sof7nG2CrY02HSGASrvTJIRxV8e0lcxDykwHYT-uhxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});