// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwondevcvfikoasscjyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3b25kZXZjdmZpa29hc3Njanl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzE0ODMsImV4cCI6MjA2ODg0NzQ4M30.8zzxXsR-p_ZJsNskcxx08dXdZj1883mSxDuBpUR5V2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});